Feldspar/feldspar-language

- src/Feldspar/Stream.hs
- tests/Feldspar/Stream/Test.hs
- tests/SemanticsTest.hs
ed79b5a fixes the output of the recurrence combinators.
@josefs, I'm not sure if the old behavior was intentional, but the provided test for `iir` shows that it now behaves consistently with a Haskell reference.
Also, following up on my comment in 640d57d, the tests in this PR speak for the correctness of that commit.
> Recurrence

- feldspar-language.cabal
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/UntypedRepresentation.hs
- src/Feldspar/ValueInfo.hs
The ValueInfo module defines a universal domain for representing sets of
values in the form of ranges (taken from the Range module) while
UntypedRepresentation has been updated with a new type for annotated
terms. The FromTyped module uses the annotated terms to record the
range information from the typed AST.
> Add range information to untyped terms.

- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Middleend/LetSinking.hs
- src/Feldspar/Core/UntypedRepresentation.hs
When compiling for target BA it is necessary that there are
no let-bindings outside the outermost lambda in the program.
Otherwise fromCore will generate a program with top level
entities that are not functions, something the BA back end
currently does not handle.
> Ensure that there are no lets outside outermost lambda for BA.

- feldspar-language.cabal
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/UntypedRepresentation.hs
This will allow variable names created
by transformations to be derived from
the variable name that prompted the creation.
> Add a string to Var type

- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Interpretation/Typed.hs
The -XOverlappingInstances language extension (a.k.a pragma LANGUAGE OverlappingInstances) is deprecated in favour of fine-grained per instance pragmas.
> Avoid deprecated pragma

- src/Feldspar/ValueInfo.hs
setLB and setUB sets the lower and upper bound of the ranges
in a ValueInfo object whereas addVI and mulVI add and multiply
the underlying ranges.
> Add functions for manipulating ValueInfo objects.

- src/Feldspar/Core/UntypedRepresentation.hs
- tests/gold/monadicSharing.txt
- tests/gold/trickySharing.txt
In the AST, let expressions are represented by the 'Let' operator
which takes the RHS and a lambda expression as arguments. Hence
'let x = rhs in e' is represented as 'Let rhs (\x.e)'. This form
is harder to read when inspecting intermediate code and it also
leads to excessive indentation when the body is another let
expression. Hence we instead format a let nest of the form
'Let e1 (\x1. Let e2 (\x2. ... Let en (\xn.e)...))' as
'Let
x1 = e1
x2 = e2
...
xn = en
In
e'
to make it more readable.
> Improve layout of 'Let' when drawing ASTs.

- src/Feldspar/Core/UntypedRepresentation.hs
When ValueInfo is included in a pretty print it is typically adjacent
to the corresponding type. Hence it is only the ranges that are
interesting, not the ValueInfo constructors. Also, the VIProd
constructor is used for a number of purposes, including arrays and
tuples, where we can print in a more idiomatic way that is also
closer to the printing of value info in the typed AST.
> Add pretty print for value info.

- src/Feldspar/Core/Constructs.hs
The incremental CSE needs the TypeF constraint in manny places,
hence it is included in SyntacticFeld when compiling with
INCREMENTAL_CSE. We will now also need the TypeF constraint in
FromCore (in feldspar-compiler), so we change SyntacticFeld
to always require TypeF.
> Add TypeF constraint to SyntacticFeld.

- feldspar-language.cabal
- src/Feldspar/Core/Middleend/Expand.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
In a loop nest, an expression may depend on the index variable
of the innermost loop but be invariant with respect to an outer loop.
In these cases we memoize the expression using an array indexed
by the innermost loop index variable.
> Add pass to memoize partially loop invariant expressions.

- feldspar-language.cabal
- src/Feldspar/Core/Middleend/Constructors.hs
- src/Feldspar/Core/Middleend/OptimizeUntyped.hs
- src/Feldspar/Core/Middleend/PushLets.hs
- src/Feldspar/Core/UntypedRepresentation.hs
- tests/gold/example9.txt
- tests/gold/topLevelConsts.txt
This commit fine-tunes the movement of bindings by the PushLet
pass so that
- a binding is left as soon as it is known to be needed (strict),
- unless there is only one static occurrence of the variable and
that occurrence is not inside a loop body.
It also does not move bindings whose rhs is a task (Future,
ParFork) or should not be inlined (NoInline).
In OptimizeUntyped, reductions of selectors is inhibited if the
corresponding tuple components are sharable (that is, nonatomic).
> Fine-tune movement of bindings and inling decisions.

- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/Types.hs
- tests/gold/monadicSharing.txt
- tests/gold/topLevelConsts.txt
- tests/gold/trickySharing.txt
This patch adds size (range) information to the typed variant
of the abstraxt syntax by redifining the Info type in Representation.
The size information is initialized to top when reifying the
program; size propagation will be the task of a separate pass.
The changes introduced in Representation leads to further
changes, mainly to strengthen contexts to enable the use
of operations from the Lattice and Eq classes on expressions
now also containing size information.
Equality is defined to require the size information to match. This
might lead to hash collisions in the CSE, but it is unlikely as the
size information is initialized to top for the corresponding type,
and the types are used when computing the hash values.
> Add size info to the typed abstract syntax.

- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/SizeProp.hs
- src/Feldspar/Core/Types.hs
The main change is in the Representation module, in the function
showAExpr. This required 'Show (Size a)' for polymorphic types
in the AST, which necessitated the rest of the changes, in
particular adding 'Show (Size a)' to the supercalss context of
the TypeF class.
> Show size info when pretty printing the typed representation.

- feldspar-language.cabal
- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Middleend/FromTypeUtil.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Middleend/OptimizeUntyped.hs
- src/Feldspar/Core/NestedTuples.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/Semantics.hs
- src/Feldspar/Core/SizeProp.hs
- src/Feldspar/Core/Types.hs
- src/Feldspar/Core/UntypedRepresentation.hs
This commit adds nested tuples to Feldspar. This allows Feldspar programs
to use tuples of arbitrary length, though not through the use of Haskell
tuple syntax. It is also possible to write for instance length independent
zip functions. Nested tuples are translated to the existing untyped tuples
which are already arbitrary length.
The existing support for tuples of length up to 15 is left as-is, so
using tuple syntax (,,,) yields the old tuples.
> Add nested tuples

- src/Feldspar/BitVector.hs
- src/Feldspar/Core/Constructs.hs
- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Render.hs
- src/Feldspar/FixedPoint.hs
- src/Feldspar/Option.hs
- src/Feldspar/Repa.hs
- src/Feldspar/SimpleVector/Internal.hs
- src/Feldspar/SimpleVector/Push.hs
- src/Feldspar/Vector.hs
The old ASTF type is parameterized on a domain, but the new CSE does
not need that parameterization. It was however left as a phantom type
parameter, which is what we now remove. This allows us to remove also
remove the corresponding parameterization from the Syntactic class.
> Remove domain type parameter from ASTF.

- src/Feldspar/Core/Middleend/FromTypeUtil.hs
- src/Feldspar/Core/Middleend/OptimizeUntyped.hs
- src/Feldspar/Core/UntypedRepresentation.hs
- tests/gold/example9.txt
- tests/gold/monadicSharing.txt
- tests/gold/topLevelConsts.txt
- tests/gold/trickySharing.txt
This is just the plumbing, there
is still no user interface.
This mirrors the type structure
in feldspar-compiler.
> Add SIMD vector (:#) to Type

- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Types.hs
- src/Feldspar/Range.hs
We no longer support GHC 7.8 so remove
the ifdefs and CPP extensions for it.
> Remove GHC 7.8 leftovers

- src/Feldspar/Core/Language.hs
This construct has been deprecated for
years and there are no in-tree users,
remove it.
> Remove deprecated select

- .travis.yml
- feldspar-language.cabal
Test with a more recent compiler rather than
an old compiler we no longer use.
> travis: bump ghc version for testing

- feldspar-language.cabal
Use -freduction-depth instead like the message
says.
> Fix deprecated -fcontext-stack message

- src/Feldspar/Core/Types.hs
Some modules in feldspar-compiler need the constructors for these
types.
> Export constructors for IntN and WordN.

- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/SizeProp.hs
Require contexts when building the AST
rather than when inspecting the AST.
> Add Show and Lattice to Info

- src/Feldspar/Core/AdjustBindings.hs
- src/Feldspar/Core/Eval.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Middleend/PassManager.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/SizeProp.hs
- src/Feldspar/Core/UntypedRepresentation.hs
Require contexts when building the AST
rather than when inspecting the AST.
> Add TypeF to AExpr

- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/SizeProp.hs
Inlining a few functions makes it obvious
to the type checker that some contexts
are present.
> Inline functions to reduce contexts

- src/Feldspar/Core/Eval.hs
- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/SizeProp.hs
This is one part of eliminating contexts from
some function signatures.
> Put Typeable on Var

- src/Feldspar/Core/Constructs.hs
- src/Feldspar/Core/Frontend.hs
This is no longer needed since the TypeF context
has been pushed into the GADTs that need it.
> Remove TypeF from SyntacticFeld

- src/Feldspar/Core/Constructs.hs
- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Language.hs
This is just an alias for Syntactic so use that
directly instead.
> Remove SyntacticFeld

- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
The pattern matching in SizeProp now includes enough
context for us to not need the context on "Info a"
so remove the context. Also wiggle some other contexts
to align definitions.
> Use higher level information for Info

- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Reify.hs
This shortens the instances for tuples
and keeps Reify-internal details inside
Reify. NFC.
> Use sugarSym for desugaring tuples

- src/Feldspar/Core/Language.hs
There is only a single value with this type but
putting the right information in place saves us
the import of Lattice.
> Tweak info on ()

- src/Feldspar/ValueInfo.hs
These are knock-on effects from the context
trimming in Range.
> Trim contexts in ValueInfo

- src/Feldspar/Core/Middleend/UniqueVars.hs
- src/Feldspar/Core/SizeProp.hs
- src/Feldspar/Core/UntypedRepresentation.hs
These Maps carry variables that we will access
so use the strict version of the map.
> Use strict version of Data.Map

- src/Feldspar/Core/Eval.hs
- src/Feldspar/Core/Representation.hs
I went too far when pushing contexts inwards earlier,
the code gets easier to modify when contexts
are further out. There seems to be a delicate
balance between contexts on functions and
contexts in data structures.
> Move Typeable upwards

- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
- tests/gold/example9.txt
This avoids hashing F2I and other conversion
operators to the same hash value. This is
a step towards reducing the need for TypeF.
> Add the type of operators to the hash value

- src/Feldspar/Core/Representation.hs
Literal is in Type so use typeRep instead to eliminate
one more use of TypeF.
> Use typeRep for Literal

- src/Feldspar/Core/NestedTuples.hs
- src/Feldspar/Core/Types.hs
- src/Feldspar/Range.hs
This is automatic for all data types since GHC 7.10
according to the documentation so remove the derives.
> Remove deriving Typeable, NFC

- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
- tests/gold/example9.txt
This switches the reification machinery
to hashing the types of leaves using Typeable.
This eliminates the need for TypeF for those
parts of Feldspar.
> Hash type into leaves in Reify

- src/Feldspar/Core/NestedTuples.hs
- src/Feldspar/Core/Types.hs
Try to avoid general names in the public namespace. This name
also collides with the Select in Vector.hs so rename it to
TSelect since we are selecting on tuples.
> Rename Select to TSelect

- feldspar-language.cabal
- src/Feldspar/Core/Interpretation.hs
- src/Feldspar/Core/UntypedRepresentation.hs
These are boilerplate instances so let
the compiler derive them.
> Derive Lift instances

- feldspar-language.cabal
- src/Feldspar/Core/Interpretation.hs
- src/Feldspar/Core/UntypedRepresentation.hs
Reverts Feldspar/feldspar-language#310
This breaks feldspar-compiler, revert for now.
> Revert "Derive Lift instances"

- src/Feldspar/Core/Types.hs
The implementation came commented out with
the initial import in 2012. Re-enable the
commented out implementation.
> Implement toTarget for Complex a

- src/Feldspar/Range.hs
These are boilerplate instances so let
the compiler derive them.
> Derive Lift for Range and WordN

- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Types.hs
This is essentially a structurally recursive way
to signal that int/unsigned int are X bits wide
on an architecture. Remove this functionality
since it is unused and re-implement it somewhere
lower down in Feldspar.
> Remove unused toTarget method

- src/Feldspar/Range.hs
The range tests hang when testing prop_or on Int32
so make Word32 the unsigned representation of Int32.
This aligns the definition of Int32 with the other
signed types in UnsignedRep.
> Make Word32 the UnsignedRep of Int32

- src/Feldspar/Range.hs
Things should be accurate by default so
remove that part of the name since it does not
convey any extra information.
> Remove Accurate suffix on functions

- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
This enforces the result to be a first-order type.
> Require result of sugarSymN to be in Type

- src/Feldspar/Core/Language.hs
The sugarSymN functions only need Typeable
for their arguments after the latest round
of changes to tuples.
> Weaken context for sugarSymN

- .travis.yml
- feldspar-language.cabal
This is not required with GHC 7.10 and later.
> cabal: Remove base-orphans package

- feldspar-language.cabal
Limit to 4 cores to avoid performance problems
from GHC scalability issues on 16+ core machines.
> cabal: run tests in parallel

- src/Feldspar/Vector/Shape.hs
This is not used after we started using elements
for materializing push vectors.
> Remove unused forShapeR

- src/Feldspar/Compiler/Backend/C/CodeGeneration.hs
- src/Feldspar/Compiler/Backend/C/Options.hs
- src/Feldspar/Compiler/Backend/C/Platforms.hs
- src/Feldspar/Compiler/Plugin.hs
Print literals directly in CodeGen.hs instead.
This saves us a bogus Lift instance for a function
type.
> Remove values in Platform

- src/Feldspar/Compiler/Backend/C/Options.hs
- src/Feldspar/Compiler/Plugin.hs
These are boilerplate instances so let
the compiler derive them.
> Derive Lift for Platform and Options

- .gitignore
The tests in feldspar-compiler had some
gitignore lines for the generated output.
Reinstate those lines and add the parser
tests and build test outputs in this
gitignore.
> Add new test output to .gitignore

- feldspar-language.cabal
This is not required with the GHC versions we use.
> cabal: remove base-compat dependency

- src/Feldspar/Core/Representation.hs
No warnings in this file so enable -Werror
before we introduce new warnings.
> Enable -Werror for Representation.hs

- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
Inline a function, use flip (:) instead of introducing
a name for it, add some linebreaks and add some TODOs
for missing documentation.
> Minor cleanups + add documentation TODOs

- feldspar-language.cabal
- tests/RegressionTests.hs
Using a ghc found in the path might cause
the tests to use a different ghc than
the ghc that built them. These situations
are tricky to trouble shoot when they
go wrong so use the same compiler.
> tests: use the right GHC

- src/Feldspar/Compiler/Backend/C/CodeGeneration.hs
- src/Feldspar/Compiler/Imperative/ExternalProgram.hs
- src/Feldspar/Compiler/Imperative/FromCore.hs
- src/Feldspar/Compiler/Imperative/Representation.hs
- src/Feldspar/Compiler/Plugin.hs
- src/Feldspar/Core/UntypedRepresentation.hs
This adds string literals to UntypedRepresentation
and the layers below that. This enables us to represent
the constant pi on the Program level.
> Add string literals

- benchs/BenchmarkUtils.hs
- benchs/CRC.hs
- benchs/FFT.hs
- benchs/FIR_Fusion.hs
- benchs/MatMul.hs
- benchs/MatMulC.c
- benchs/MatMulC.h
- feldspar-language.cabal
Leave the FFT and MatMul benchmarks disabled for now:
- The FFT benchmark uses Eq (Data a) which is a binding
time violation.
- The MatMul benchmark has something strange with
the test input/output array representation.
> Import benchmarks from feldspar-compiler

- feldspar-language.cabal
We use GADTs in some places and that implies MonoLocalBinds. For
the other places we get simplifiable class constraint warnings
from GHC 8.2 and later. This does not just silence the warnings,
it appears to be what we want.
> Enable MonoLocalBinds

- src/Feldspar/Compiler/Backend/C/CodeGeneration.hs
- src/Feldspar/Compiler/Backend/C/Platforms.hs
- src/Feldspar/Compiler/Imperative/Representation.hs
- src/Feldspar/Compiler/Options.hs
- src/Feldspar/Core/Middleend/Expand.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Middleend/OptimizeUntyped.hs
- src/Feldspar/Core/UntypedRepresentation.hs
- src/Feldspar/Core/ValueInfo.hs
This is a step in fixing orphan instances
by shifting things around to avoid cyclic
imports.
> Move ValueInfo utils to ValueInfo.hs

- feldspar-language.cabal
- src/Feldspar/Core/Reify.hs
This is an attempt to get stable variable names
in our test outputs across GHC versions. This part
works locally for me with GHC 8.8.3 now.
> Normalize typerep output

- .travis.yml
- tests/Feldspar/Range/Test.hs
Ubuntu 20 ships with GHC 8.8 so add that to the build.
Using shiftL/shiftR with a negative amount throws an arithmetic
exception in this version of GHC so stop doing that in our
tests.
> travis: add GHC 8.8

- src/Feldspar/Compiler.hs
This pass is a no-op for other platforms so there
is no need to make it code generator specific.
> Always run adaptTic64x, NFC

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/ExternalProgram.hs
- src/Feldspar/Compiler/Options.hs
- src/Feldspar/Core/Frontend.hs
This enables the either construction from
the backend so one can input multiple formats
into the same pipeline.
> Factor out reifyFeld from frontend again

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/Options.hs
- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Middleend/PassManager.hs
Since we no longer have more than one pass enumeration
type, rename FrontendPass to Pass and make PassCtrl
contain lists of Pass.
> Make PassCtrl monomorphic

- src/Feldspar/Compiler/Backend/C/MachineLowering.hs
- src/Feldspar/Compiler/Backend/C/Tic64x.hs
- src/Feldspar/Compiler/Imperative/FromCore.hs
- src/Feldspar/Compiler/Imperative/Representation.hs
Remove the unused parameter for now.
The general question of how to always
generate portable code even for oddball
platforms still remains.
> Remove unused parameter on "extend"

- src/Feldspar/Core/SizeProp.hs
It is the pattern match checker that makes this
file take minutes to compile. Disable the warnings
for now.
> Fix compilation times for GHC 8.6+ on SizeProp.hs

- src/Feldspar/Core/Middleend/FromTyped.hs
Disable pattern match warnings for this file
instead.
This reverts commit f84cd7a81921a9b6298638de12000dc499bc6398.
> Revert "Fix compilation time issue for FromTyped.hs"

- stack.yaml
There is support for -jN to ghc --make but there
is only a speedup for small values of N. Pass -j3
since that gives a speedup on my machine.
> stack: add -j3 to ghc-options for $local

- stack-8.4.4.yaml
Keep the previous stack.yaml as stack-8.4.4.yaml.
> stack: use LTS-16.5

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/Options.hs
This is a better name since we no longer have
the artificial distinction between backend
and frontend passes.
> Rename frontendCtrl to passCtrl

- src/Feldspar/Core/Middleend/OptimizeUntyped.hs
The type to use for the computation is the return
type of Mul/Div, not whatever we entered simpApp with.
> Use the right type for Mul/Div constant folding

- benchs/MatMul.hs
- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/Options.hs
- src/Feldspar/Core/Frontend.hs
- tests/RegressionTests.hs
These are leftovers from the repo-split, put
the targets in the platform since that is
essentially what we use it for anyway.
Remove the unused constructors and the corresponding
option record definitions (sicsOptions*).
> Push targets into Platform

- src/Feldspar/Compiler/Backend/C/MachineLowering.hs
- src/Feldspar/Compiler/Options.hs
- tests/RegressionTests.hs
- tests/gold/complexWhileCond.c
- tests/gold/complexWhileCond.h
The extend function used the platform to lookup
the name of certain types so the Destination had
to carry the platform as a parameter. Since
we use regular C99 names everywhere this parameter
can now be removed.
> Remove unused argument in Destination type

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/ExternalProgram.hs
- src/Feldspar/Compiler/Imperative/FromCore.hs
- src/Feldspar/Compiler/Options.hs
- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Middleend/Constructors.hs
- src/Feldspar/Core/Middleend/CreateTasks.hs
- src/Feldspar/Core/Middleend/LetSinking.hs
- src/Feldspar/Core/Middleend/UniqueVars.hs
- src/Feldspar/Core/UntypedRepresentation.hs
- tests/gold/tfModel.txt
This allows us to remove the un-annotation pass which
is a leftover from the split repositories. Long-term
this will allow us to carry annotations from
the frontend all the way down into the code generation.
> Convert fromTypedUT to use AUntypedFeld

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/Imperative/FromCore.hs
- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Middleend/Constructors.hs
- src/Feldspar/Core/Middleend/CreateTasks.hs
- src/Feldspar/Core/Middleend/Expand.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Middleend/LetSinking.hs
- src/Feldspar/Core/Middleend/OptimizeUntyped.hs
- src/Feldspar/Core/Middleend/PushLets.hs
- src/Feldspar/Core/Middleend/UniqueVars.hs
- src/Feldspar/Core/UntypedRepresentation.hs
- src/Feldspar/Core/ValueInfo.hs
- tests/RegressionTests.hs
After the removal of the un-annotated UntypedFeld,
we can now use that name for the annotated representation.
> Rename AUntypedFeld to UntypedFeld, NFC

- src/Feldspar/Core/NestedTuples.hs
- src/Feldspar/Core/Semantics.hs
- src/Feldspar/Option.hs
- tests/RegressionTests.hs
This allows us to remove First and Skip by
using 0.. instead.
I am not sure why but this change also enables
GHC to not require additional function bindings
in Option.hs.
> Use type-level naturals for tuple selection

- src/Feldspar/Core/NestedTuples.hs
- src/Feldspar/Core/Tuple.hs
- src/Feldspar/SimpleVector/Internal.hs
- src/Feldspar/Vector.hs
The tuple support we need can be built on top
of NestedTuple so do that. The reason the initial
implementation of Tuple did not do that was because
the support for NestedTuples was not implemented.
> Build Tuple from NestedTuple

- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Tuple.hs
- src/Feldspar/Core/Types.hs
This avoids some namespace pollution and moves
us one step closer to being able to define generic
N-bit types without a lot of boilerplate.
> Use type level literals as witnesses

- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Tuple.hs
- src/Feldspar/Core/Types.hs
- tests/RegressionTests.hs
- tests/gold/pairRet.c
- tests/gold/pairRet.h
We can build tuples from nested tuples by changing
TypeRep for tuples from taking k type parameters
into taking a Tuple with k type variables. This
makes Size and Type instances trivial since they
just need to forward to the same mechanics
for Tuple.
> Build tuples on nested tuples

- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/Types.hs
- tests/Feldspar/Range/Test.hs
There is only a single value for unit but our
ranges can handle that so treat things uniformly.
> Add a Range information for unit

- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/SizeProp.hs
- src/Feldspar/Core/ValueInfo.hs
- src/Feldspar/Range.hs
This is in preparation for having multiple
Lattice (Range a) instances with different
implementations.
> Use fullRange instead of universal in Range

- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Types.hs
- src/Feldspar/Range.hs
- tests/Feldspar/Range/Test.hs
The ranges are not yet useful since they contain
-Inf..Inf, but we have at least started carrying
them around.
> Add Range information for Float/Double

- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Representation.hs
This removes FiniteBits a and Integral/FiniteBits
for UnsignedRep a.
> Shrink Integral contexts

- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/Types.hs
Other classes often imply Type a, there are for example
no instances of Num a where a is not in Type in Feldspar.
Remove the Type a in Op on those classes, except for the
two places where it is currently required for SizeProp.
> Reduce contexts in Op

- src/Feldspar.hs
- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/Types.hs
- src/Feldspar/Option.hs
- src/Feldspar/Repa.hs
- src/Feldspar/Vector.hs
Tuples are an essential part of the core language
and nested tuples are just a different implementation.
Provide the nested tuples by default when importing
Feldspar. Also stop re-exporting nested tuples from type
to reduce dependencies within Feldspar.
> Export nested tuples from Feldspar

- src/Feldspar/Compiler.hs
These are no longer used outside the module so stop
exporting them.
> Stop exporting internal functions from Compiler

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/Plugin.hs
- tests/RegressionTests.hs
The output filename is available in Options
so use that instead of passing it as an extra
parameter.
> Remove filename parameter from compile

- src/clib/include/taskpool.c
Returning from the function is the same as
calling pthread_exit() but avoids warnings
from GCC about the function not having
a return value.
> Make explicit return from worker()

- feldspar-language.cabal
This does not work so remove it. The relevant
parts of the RTS should be spliced into the same
output file as the rest of the program.
> Stop including the RTS in libHSFeldspar.a

- tests/RegressionTests.hs
I mixed up what the OS is called, apparently it is called
mingw32 by GHC and windows by cabal. Fix the ifdefs to use
what is defined. This makes the tests pass on Windows.
> tests: use the right ifdef name

- src/Feldspar/Compiler/Imperative/ArrayOps.hs
- src/Feldspar/Compiler/Imperative/FromCore.hs
- src/Feldspar/Compiler/Imperative/Representation.hs
- src/Feldspar/Core/Middleend/Expand.hs
- src/Feldspar/Core/Semantics.hs
Things have moved around in the Prelude since GHC 8.0
so we had double imports/hides in some places. Remove
those now that we only support 8.8 and later.
> Fix GHC 8.8 warnings

- src/Feldspar/Core/NestedTuples.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Types.hs
- tests/RegressionTests.hs
Trying to keep the Hashable instances in a single
place creates orphan warnings so that was a bad
idea. Move them back to where they belong.
> Move Hashable (Tuple a) back to NestedTuple

- feldspar-language.cabal
- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/Plugin.hs
- tests/RegressionTests.hs
This gives us the right platform behavior/output
with respect to slashes in paths.
> Use System.FilePath to construct paths

- src/Feldspar/Compiler/Backend/C/CodeGeneration.hs
These are unused outside the module so stop exporting
them.
> Trim export list in CodeGeneration.hs

- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/ValueInfo.hs
- tests/gold/example9.txt
- tests/gold/tfModel.txt
- tests/gold/topLevelConsts.txt
This is a Range Int for legacy reasons, switch to Range bool.
This fixes the printing of the full boolean range
to print as [*,*].
> Use Range Bool for VIBool

- feldspar-language.cabal
- src/Feldspar/Onnx/onnxToFeld.hs
Add code to write a weight file based on the initializations
in the ONNX model. This avoids putting all of the weights of
the model, whic can amount to gigabytes, in the generated
program.
Generate Feldspar syntax from the nodes in the model graph.
> Improve onnxToFeld

- feldspar-language.cabal
This speeds up writing the data file
for resnet50-v2-7.onnx with a couple
of seconds on my computer.
> cabal: enable -O2 for onnxToFeld

- feldspar-language.cabal
- src/Feldspar/Onnx/onnxToFeld.hs
The show instances for Float/Double work hard
print the shortest string that represents
the number. Use a different show instance
to save ~50 Gb of allocations on resnet50-v2-7.onnx
and speed things up.
> Use fshow to speed up onnxToFeld

- src/Feldspar/Onnx/onnxToFeld.hs
This is not required if the argument is a single string.
> Remove superfluous $-sign after error

- src/Feldspar/Vector.hs
There is no need for these to be open families.
> Close the Shape type families in Vector

- src/Feldspar/Onnx/onnxToFeld.hs
There is a model name in ONNX, it just happens
to be "main" for resnet50. Mangle the name to
avoid clashing with the main function
of the program.
> Use the model name in onnxToFeld

- src/Feldspar/Compiler/Imperative/FromCore.hs
- src/Feldspar/Compiler/Imperative/Frontend.hs
- tests/gold/arrayInStruct.c
- tests/gold/arrayInStruct.h
- tests/gold/arrayInStructInStruct.c
- tests/gold/arrayInStructInStruct.h
- tests/gold/arrayInStruct_openMP.c
- tests/gold/arrayInStruct_openMP.h
- tests/gold/arrayInStruct_wool.c
- tests/gold/arrayInStruct_wool.h
- tests/gold/complexWhileCond.c
- tests/gold/complexWhileCond.h
- tests/gold/deepArrayCopy.c
- tests/gold/deepArrayCopy.h
- tests/gold/ivartest2.c
- tests/gold/ivartest2.h
- tests/gold/metrics.c
- tests/gold/metrics.h
- tests/gold/pairParam.c
- tests/gold/pairParam.h
- tests/gold/pairParam2.c
- tests/gold/pairParam2.h
- tests/gold/pairParam_ret.c
- tests/gold/pairParam_ret.h
- tests/gold/pairRet.c
- tests/gold/pairRet.h
Struct types with many fields get very long tags in the generated code.
This is a problem for the weight dictionaries created by onnxToFeld. We
solve the problem by abbreviating sequences of fields with the same type
using run length encoding.
> Make tags shorter for some generated structs.

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/Backend/C/CodeGeneration.hs
- src/Feldspar/Compiler/Imperative/FromCore.hs
- src/Feldspar/Compiler/Imperative/Representation.hs
This removes the ad-hoc handling of appending
some extra strings for include files
in compileSplitModule by adding an entity to
represent include files.
> Add an entity for include files

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/Backend/C/CodeGeneration.hs
- src/Feldspar/Compiler/Options.hs
Splitting a module into a header and an implementation
is an internal detail of BPCompile so merge the functionality
in there and remove BPSplit as a pass.
This gives us one pass less to keep track of
and also simplifies the type signatures for frontend
and codegen.
> Remove BPSplit as a pass

- stack.yaml
We were already using GHC 8.8.4 so switch
to a version that uses it by default.
> stack: update to LTS-16.12

- hie.yaml
The file is moved into the right place so remove
the special entry.
> hie: remove special onnxToFeld path

- feldspar-language.cabal
The regression tests get a speedup
when using more cores, the balance
currently seems to be the number
of real cores+some. Use 12 since
the Travis instances has 16 "cores"
available.
> tests: enable more cores

- src/Feldspar/Core/Middleend/PushLets.hs
This is a temporary fix of the space leak by increasing strictness.
It is intended to be replaced by either:
- A somewhat restructured PushLets pass that does not need the fix, or
- a permanent strictness fix in terms of DeepSeq.
> Fix a space leak in PushLets.
