Feldspar/feldspar-language

- src/Feldspar/Core/Constructs/MutableToPure.hs
A small step towards size propagation for monadic expressions.
This pull request transfers what little is known about the mutable array size to the pure array.
/cc @emilaxelsson
> Add size propagation for `WithArray`

- src/Feldspar/Range.hs
Some utility functions in Range only need
a single class, for example Ord or Bits.
Remove the unused classes. NFC.
> Reduce type class dependencies in Range

- src/Feldspar/Core/UntypedRepresentation.hs
This commit mainly adds support functions for manipulating
annotated terms (AUntypedFeld a). It also changes the stringTree
function to print (more) type information.
> Add some support functions.

- feldspar-language.cabal
Add flag to Cabal file enabling incremental CSE.
> Add flag for enabling incremental CSE.

- feldspar-language.cabal
- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Types.hs
- src/Feldspar/Seq.hs
- src/Feldspar/SimpleVector/Internal.hs
- src/Feldspar/Stream.hs
- src/Feldspar/Vector.hs
The incremental CSE is based on hashing, so we import Data.Hash and add Hashable to some contexts.
> Enable hashing in preparation for new CSE.

- src/Feldspar/Core/Constructs.hs
- src/Feldspar/Core/Types.hs
The TypeF class allows us to construct a TypeRep also for function types.
> Add class TypeF

- src/Feldspar/Core/Middleend/OptimizeUntyped.hs
The OptimizeUntyped pass makes constant folding, algebraic simplification
and dead code elimination optimizations. This commit is a major
overhaul that in particular improves transformations across variable
bindings (lets). It also adds several additional constant folding rules.
> Improve the untyped optimizer.

- src/Feldspar/Vector.hs
Using parallel to write a multidimensional pull vector to memory
requires the use of the fromIndex function which generates div
and mod operations to construct a multidimensional index from a
linear index. Hence it is better to use nested loops and toIndex
which only multiplies and adds.
> Use elements in fromPull.

- src/Feldspar/Core/UntypedRepresentation.hs
Add a pretty printing function with more compact output than
the the tree-based functions. The more compacts layout
improves both performance and readability for very large
programs.
> Add compact pretty printing function.

- feldspar-language.cabal
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Middleend/PassManager.hs
This commit adds a pass manager that handles control of which
passes to run and which intermediate versions of the program
to pretty print.
> Add a pass manager and use it for the front-end.

- feldspar-language.cabal
- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/SizeProp.hs
- src/Feldspar/Core/Tuple.hs
- tests/gold/topLevelConsts.txt
This size inference is mainly geared towards finding sizes of
data structures. It is derived from and largely identical to
the size inference associated with the non-incremental CSE.
> Add size inference when using incremental CSE.

- src/Feldspar/Core/Types.hs
These type families were introduced before
there were closed type families. We want
closed type families here so close them.
> Close the type families in Types

- src/Feldspar/Core/SizeProp.hs
> Replace TypeF with Typeable

- feldspar-language.cabal
This is handled on a file by file basis
by the LANGUAGE pragmas.
> Remove deprecated other-extensions

- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Types.hs
- src/Feldspar/Range.hs
There is a show instance that does the same
thing so use it.
> Use show instance for CBind

- src/Feldspar/Core/AdjustBindings.hs
- src/Feldspar/Core/Constructs.hs
- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Interpretation.hs
- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Middleend/Constructors.hs
- src/Feldspar/Core/Middleend/Expand.hs
- src/Feldspar/Core/Middleend/FromTypeUtil.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Middleend/OptimizeUntyped.hs
- src/Feldspar/Core/Middleend/PassManager.hs
- src/Feldspar/Core/Middleend/PushLets.hs
- src/Feldspar/Core/NestedTuples.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Types.hs
- src/Feldspar/Core/UntypedRepresentation.hs
- src/Feldspar/SimpleVector/Push.hs
There is a type for this so use it.
> Use existing type name

- src/Feldspar/Core/Eval.hs
- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/SizeProp.hs
Shuffle things around to eliminate more
contexts.
> Remove more contexts on functions

- src/Feldspar/Core/SizeProp.hs
This inlines spLambda so the information gained
by pattern matching can be used in the RHS.
> Inline spLambda to remove ctxts

- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/Types.hs
Push things around and remove various functions
to reduce context dependencies.
> Tweak contexts some more

- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/SizeProp.hs
The context information is available after pattern
matching and it also reduces the number of lines
of code.
> Inline more in SizeProp

- src/Feldspar/Range.hs
This is preparatory work for adding fixed point
numbers.
> Shrink contexts in Range

- src/Feldspar/Core/Constructs.hs
- src/Feldspar/Core/Eval.hs
- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Render.hs
- src/Feldspar/Core/Syntactic.hs
Move some functions into Reify and others out
of Reify.
> Move functions between modules

- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Reify.hs
This gives some kind of error message hinting of where we
end up if things go wrong.
> Replace undefined with error

- src/Feldspar/Core/Constructs.hs
- src/Feldspar/Core/Interpretation.hs
- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/UntypedRepresentation.hs
- src/Feldspar/Par.hs
Frontend is the interface to the programmer
so use that.
> Import Frontend instead of Constructs

- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Reify.hs
The context at the use site carries this information
so leverage that instead.
> Remove some TypeF requirements

- src/Feldspar/Core/Reify.hs
The function catchBindings with an empty list
does the same thing.
> Remove fromCExp

- src/Feldspar/Core/Language.hs
This is a double sugar so remove one of them.
> Remove Data on sugar for tuples

- src/Feldspar/SimpleVector/Internal.hs
- src/Feldspar/Vector.hs
This is the Feldspar tuple mechanics so use
that instead of the external Data.Tuple.
> Use Feldspar.Core.Tuple

- src/Feldspar/Core/Frontend.hs
This function is identical to reifyFeld.
> Remove reifyFeldM

- src/Feldspar/Range.hs
This reduces the required context
for Num (Range a).
> Use FixedBits to implement bits

- src/Feldspar/Core/Language.hs
This is a sibling to commit 0be7fd424b9.
> Remove Data in SyntacticTup (a :* b) instance

- src/Feldspar/Core/Language.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/SizeProp.hs
- src/Feldspar/Option.hs
- src/Feldspar/Repa.hs
- src/Feldspar/SimpleVector/Internal.hs
These definitions are the same so use one of them
instead of both.
> Use top instead of universal

- src/Feldspar/Core/UntypedRepresentation.hs
We should not share things that are unsharable
in the first place.
> Remove unused utility function

- src/Feldspar/Core/Middleend/FromTyped.hs
Use the information we have instead of
defaultSize.
> Fix info in toU

- feldspar-language.cabal
- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Middleend/Expand.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Middleend/OptimizeUntyped.hs
- src/Feldspar/Core/UntypedRepresentation.hs
- src/Feldspar/Core/ValueInfo.hs
This is an internal module for the middleend.
> Move ValueInfo to Core

- src/Feldspar/Core/AdjustBindings.hs
- src/Feldspar/Core/Collection.hs
- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Interpretation.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/NestedTuples.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/Semantics.hs
- src/Feldspar/Core/SizeProp.hs
- src/Feldspar/Core/Tuple.hs
- src/Feldspar/Core/Types.hs
- src/Feldspar/Core/UntypedRepresentation.hs
- src/Feldspar/Core/ValueInfo.hs
Fix a bunch of warnings and disable some warnings
for some modules where it is hard to fix.
> Add -Wall flag to Core modules

- feldspar-language.cabal
- src/Feldspar/Onnx/Operators.hs
- src/Feldspar/Vector/Shape.hs
And fix some of the obvious warnings.
> cabal: add Operators library

- src/Feldspar/Onnx/Operators.hs
Use zeros from Vector to construct a zero-vector,
introduce "Attrs" as a shorthand for a list of
attributes, and break lines to make things fit
in a single column.
> Fix various style things, NFC

- src/Feldspar/Onnx/Operators.hs
Reorder and tweak equations to make the function
total.
> Make unionExt total

- src/Feldspar/Core/AdjustBindings.hs
- src/Feldspar/Core/Eval.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/SizeProp.hs
With the latest changes we have general symbols so
rename the constructor in Expr accordingly.
> Rename Operator to Sym, NFC

- examples/Examples/Simple/Basics.hs
- src/Feldspar/Algorithm/CRC.hs
- src/Feldspar/Algorithm/FFT.hs
- src/Feldspar/Core/Language.hs
- src/Feldspar/SimpleVector/Internal.hs
- src/Feldspar/Stream.hs
- src/Feldspar/Vector.hs
- tests/DecorationTests.hs
- tests/RegressionTests.hs
The new CSE loops when there are binding
time violations so remove the code that
causes that.
> Fix binding time violations

- src/Feldspar/Compiler/Backend/C/MachineLowering.hs
- src/Feldspar/Compiler/Imperative/FromCore.hs
- src/Feldspar/Core/Frontend.hs
There is no need for the UnOpt functions with the new CSE.
> Remove *UnOpt from Frontend.hs

- src/Feldspar/Compiler/Compiler.hs
- src/Feldspar/Compiler/Frontend/Interactive/Interface.hs
- src/Feldspar/Compiler/Options.hs
- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Middleend/FromTyped.hs
- src/Feldspar/Core/Middleend/PassManager.hs
- src/Feldspar/Core/Reify.hs
- src/Feldspar/Core/Representation.hs
- src/Feldspar/Core/ValueInfo.hs
This is one more step towards fixing orphan instances.
> Move PrettyInfo into ValueInfo

- src/Feldspar/Compiler/Imperative/ArrayOps.hs
- src/Feldspar/Compiler/Imperative/Frontend.hs
This allows us to remove some parameters and hopefully
simplify things a bit more in the future.
> Move array operations to ArrayOps.hs, NFC

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/Imperative/FromCore.hs
- src/Feldspar/Core/UntypedRepresentation.hs
- tests/gold/arrayInStruct.c
- tests/gold/arrayInStruct_openMP.c
- tests/gold/arrayInStruct_wool.c
- tests/gold/complexWhileCond.c
- tests/gold/concatV.c
- tests/gold/concatVM.c
- tests/gold/divConq3.c
- tests/gold/fut1.c
- tests/gold/fut1.h
- tests/gold/fut1_ret.c
- tests/gold/fut1_ret.h
- tests/gold/issue128_ex3.c
- tests/gold/ivartest.c
- tests/gold/ivartest.h
- tests/gold/ivartest2.c
- tests/gold/ivartest2.h
- tests/gold/metrics.c
- tests/gold/scanlPush.c
The test output is not stable with respect
to changes that renumber variables in the frontend.
Make fromCoreUT start numbering its own variables
from 0 and just return the Module.
> Number variables from 0 in FromCore.hs

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/ExternalProgram.hs
- src/Feldspar/Compiler/Options.hs
- src/Feldspar/Core/Frontend.hs
- src/Feldspar/Core/Middleend/CreateTasks.hs
- src/Feldspar/Core/Middleend/LetSinking.hs
- src/Feldspar/Core/UntypedRepresentation.hs
- tests/DecorationTests.hs
This does not allow us to enable the orphan
warning on Frontend but it moves us closer
to that goal.
> Move Pretty instance to data declaration

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/Options.hs
- src/Feldspar/Core/Frontend.hs
This removes parameters to various functions and enables
the user to configure the compilation pipeline.
> Merge ProgOpts into Options

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/Backend/C/CodeGeneration.hs
- src/Feldspar/Compiler/Backend/C/MachineLowering.hs
- src/Feldspar/Compiler/Backend/C/RuntimeLibrary.hs
- src/Feldspar/Compiler/Backend/C/Tic64x.hs
- src/Feldspar/Compiler/Imperative/ArrayOps.hs
- src/Feldspar/Compiler/Imperative/ExternalProgram.hs
- src/Feldspar/Compiler/Imperative/FromCore.hs
- src/Feldspar/Compiler/Imperative/Frontend.hs
- src/Feldspar/Compiler/Imperative/Representation.hs
These have been instantiated with unit
and not been used for a long time so
remove them.
> Remove the phantom variables on Program

- src/Feldspar/Core/Middleend/FromTyped.hs
The pattern match warnings are disabled so
we have compilation performance where it should
be, return to more readable code.
> Return to pattern guards in FromTyped.hs

- src/Feldspar/Compiler.hs
- src/Feldspar/Compiler/ExternalProgram.hs
- src/Feldspar/Compiler/Imperative/FromCore.hs
- src/Feldspar/Core/Frontend.hs
The pass manager removes the need for these functions.
> Remove compileToCCore'

- src/Feldspar/Compiler/Imperative/ArrayOps.hs
- src/Feldspar/Compiler/Imperative/FromCore.hs
- src/Feldspar/Compiler/Imperative/Frontend.hs
- src/Feldspar/Core/ValueInfo.hs
This is preparation for enabling Ranges
for non-integer types.
> Tweak a type signature, NFC

- src/Feldspar/Option.hs
- src/Feldspar/Repa.hs
- src/Feldspar/SimpleVector/Internal.hs
- src/Feldspar/Vector.hs
There is only one resugar nowadays so stop hiding
it to import it from some other module.
> Use resugar from Feldspar in libraries

- src/Feldspar/Core/Middleend/PassManager.hs
Add an export list and implement runPassC
in terms of runPassT.
> Tweak PassManager implementation, NFC

- src/Feldspar/Compiler.hs
Error out immediately when we detect an error
in external program input. This simplifies the logic
and untangles the IO from the external program helpers.
> Fail early in External Program

- feldspar-language.cabal
- tests/RegressionTests.hs
The tests will fail without this.
> tests: set codepage on Windows

- hie.yaml
- src/Feldspar/Core/Middleend/FromTyped.hs
This enables using hie-bios/ghcide for symbol resolution
and other things for this project.
No functional change for Stack/GHC.
> Add a hie.yaml

- feldspar-language.cabal
- src/Feldspar/Compiler/Plugin.hs
- src/Feldspar/Core/NestedTuples.hs
- tests/Feldspar/Core/Test.hs
- tests/Feldspar/Range/Test.hs
- tests/RegressionTests.hs
I missed this when preparing commit af39a02acd92.
> Use System.FilePath for constructing paths

- feldspar-language.cabal
- src/Feldspar/Onnx/onnx.proto
- src/Onnx/ModelProto.hs
- src/Onnx/TrainingInfoProto.hs
- src/Onnx/Version.hs
Update onnx.proto to latest version
and regenerate src/Onnx.
> onnx: update to latest version

- src/Feldspar/Compiler/Plugin.hs
These get in the way of our test output so filter
out the messages.
> Silence "Loaded package environment from .." msgs
